apiVersion: apps/v1
kind: Deployment
metadata:
  name: code2
  labels:
    app: code2
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: code2
        image: nginx
        ports:
        - containerPort: 8080